# 4.1 NumPy

## 4.1.1 NumPyの概要
## 4.1.2 NumPyでデータを扱う

### １次元配列、
### ２次元配列、
### 変形(reshape)、
### データ(dtype)、
### インデックスとスライス、
### データ再代入、
### 深いコピー(コピーを返す)(Shallow Copy)[Python標準リストのスライス、flattenメソッド、copy()で代入]
### 浅いコピー(参照を返す)(Deep Copy)[Numpyのスライス、ravelメソッド 、直接代入]

In [7]:
import numpy as np
a = np.array([1,2,3])
# スペース区切り、配列として出力
print(a)
# オブジェクト確認
type(a)
# 要素確認
a.shape
a[0]
a[1:]
a[-3]
a
a[2]=4
a
a1 =a
a1
a1[1]=5
a1
a1
a2=a.copy()
a2[1]=6
a2
a

[1 2 3]


array([1, 5, 4])

In [8]:
b = np.array([[1,2,3],[4,5,6]])
# スペース区切り、配列として出力
print(b)
# オブジェクト確認
type(b)
# 要素確認
b.shape
b[1,0]
b[:,[0,2]]
b[1,2]=7
b[:,2]=8
b

[[1 2 3]
 [4 5 6]]


array([[1, 2, 8],
       [4, 5, 8]])

In [17]:
c1 = np.array([0,1,2,3,4,5])
# c1 を2X3の２次元配列に変換
c2 = c1.reshape((2,3))
c2
# c2 を１次元配列に変[参照]
c3 = c2.ravel()
# c2 を１次元配列に変[コピー]
c4 = c2.flatten()
c4
# 配列要素のデータ型を確認
c4.dtype
# 型付け配列作成
d = np.array([1,2], dtype=np.int16)
d.dtype
# 型変換
d.astype(np.float16)
c3 = c2.ravel()
c4 = c2.flatten()
c3[0] =6
c4[1] =7
c2

array([[6, 1, 2],
       [3, 4, 5]])

In [23]:
py_list1 = [0,1]
py_list2  = py_list1[:]
py_list2[0] = 2
print(py_list1)
print(py_list2)
np_array1 = np.array([0,1])
np_array2 = np_array1[:]
np_array2[0] = 2
print(np_array1)
print(np_array2)

[0, 1]
[2, 1]
[2 1]
[2 1]


### 数列を返す(arange)

In [27]:
print(np.arange(10))
print(np.arange(1,11))
print(np.arange(1,11,2))

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


### 乱数

In [46]:
# タプルは引数
f = np.random.random((3,2))
print(f)
# 複数の引数
f = np.random.rand(3,2)
print(f)
# 乱数をseedで固定
np.random.seed(123)
np.random.random((3,2))
# ある範囲内の任意の整数を生成
np.random.seed(123)
np.random.randint(1,10)
np.random.seed(123)
np.random.randint(1,10,(3,3))
# ある範囲内の任意の小数値を生成
np.random.seed(123)
np.random.uniform(0.0,5.0,(2,3))
# 標準正規分布
np.random.seed(123)
np.random.randn(4,2)
#平均、標準偏差、size(形状)を引数として正規分布乱数を取得
np.random.seed(123)
np.random.normal()

[[0.34317802 0.72904971]
 [0.43857224 0.0596779 ]
 [0.39804426 0.73799541]]
[[0.18249173 0.17545176]
 [0.53155137 0.53182759]
 [0.63440096 0.84943179]]


-1.0856306033005612

### 同じ要素の数列を作る

In [53]:
# 要素が全て0.
print(np.zeros((2,3)))
# 要素が全1.
print(np.ones((2,3)))
# 要素が対角が1.その他が0.
print(np.eye(4))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 指定値で埋める

In [65]:
# 3.14を３つ埋める
np.full(3,314)
# 2x4の行列にpiを埋める
np.full((2,4),np.pi)
# Not a Numberの宣言
np.array([1,2,np.nan])
# 均等割りデータを作る(0~1の間5個のよそを作る)
print(np.linspace(0,1,5))
print(np.arange(0.0,1.1,0.25))
np.linspace(0,np.pi,21)

l = np.array([2,2,6,1,3])
# 要素間の差分を返す
np.diff(l)

[0.   0.25 0.5  0.75 1.  ]
[0.   0.25 0.5  0.75 1.  ]


array([ 0,  4, -5,  2])

### 連携

In [81]:
a = [1,5,4]
a1 = [1,5,4]
print(a)
print(a1)
# a+a1
np.concatenate([a,a1])
# ２次元配列の連携、axis=1:列方向増やす
b = np.array([[1,2,8],[4,5,8]])
b1 = np.array([[10],[20]])
np.concatenate([b,b1],axis=1)
np.hstack([b,b1])
b2 = np.array([30,60,45])
# 行方向増やす
b3 = np.vstack([b,b2])
b3

[1, 5, 4]
[1, 5, 4]


array([[ 1,  2,  8],
       [ 4,  5,  8],
       [30, 60, 45]])

### 分割

In [88]:
# 列毎に分割
first,second = np.hsplit(b3,[2])
print(b3)
print('------')
print(first)
print(second)
print('------')
# 行毎に分割
first1,second2 = np.vsplit(b3,[2])
print(first1)
print(second2)

[[ 1  2  8]
 [ 4  5  8]
 [30 60 45]]
------
[[ 1  2]
 [ 4  5]
 [30 60]]
[[ 8]
 [ 8]
 [45]]
------
[[1 2 8]
 [4 5 8]]
[[30 60 45]]


### 転置、次元追加

In [107]:
print(b)
# 行列を転置
print(b.T)
a = np.array([1,5,4])
a
# 行方向に次元追加
a[np.newaxis, :]
# 列方向に次元追加
a[:,np.newaxis]

[[1 2 8]
 [4 5 8]]
[[1 4]
 [2 5]
 [8 8]]


array([[1],
       [5],
       [4]])

### グリッドデータの作成

In [114]:
m = np.arange(0,4)
n = np.arange(4,7)
# xxにmを行方向に3回(nの長さ)コピーして入れる 
# yy にnを列方向に4回(ｍの長さ)コピーして入れる
xx,yy = np.meshgrid(m,n)
print(xx)
print(yy)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]]


## 4.1.3 Numpyの各機能

In [15]:
import numpy as np
a = np.arange(3)
b = np.arange(-3, 3).reshape((2,3))
c = np.arange(1,7).reshape((2,3))
d = np.arange(6).reshape((3,2))
e = np.linspace(-1,1,10)
# 配列確認
print("a:",a)
print("b",b)
print("c:",c)
print("d:",d)
print("e:",e)
# 要素確認
print("a:",a.shape)
print("b",b.shape)
print("c:",c.shape)
print("d:",d.shape)
print("e:",e.shape)
new = []
for i, j in enumerate(b):
    new.append([])
    for k in j:
        new[i].append(abs(k))
print(new)


a: [0 1 2]
b [[-3 -2 -1]
 [ 0  1  2]]
c: [[1 2 3]
 [4 5 6]]
d: [[0 1]
 [2 3]
 [4 5]]
e: [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
a: (3,)
b (2, 3)
c: (2, 3)
d: (3, 2)
e: (10,)
[[3, 2, 1], [0, 1, 2]]


### ユニバーサルファンクション

In [14]:
# 絶対値
np.abs(b)
# sin関数
np.sin(e)
# cos関数
np.cos(e)
# log関数
np.log(a)
# log10関数(底が10)
np.log10(c)
# eのｘ
np.exp(a)

[[3 2 1]
 [0 1 2]]


/Users/burgud/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


array([1.        , 2.71828183, 7.3890561 ])

### ブロードキャスト

In [42]:
# 配列各要素に+10
a+10
# aが2+3になり+b
a+b
# aが3行まで拡張され、a1が3x3になれ足し算
a1 = a[:, np.newaxis]
a+a1
# 各要素から引き算
c -np.mean(c)
# 各要素をかけ算
b * 2
# 各要素を2乗
b ** 2
# aを２行にして引き算
b -a
# aを２行にして引き算
a * b
# aを２行にして引き算
a / c
c / a

/Users/burgud/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:20: RuntimeWarning: divide by zero encountered in true_divide


array([[inf, 2. , 1.5],
       [inf, 5. , 3. ]])

### ドット積

In [46]:
# a =[0,1,2] x b=[[-3,-2,-1],[0,1,2]] = [(0x(-3)+1x(-2)+2x(-1)),0x0+1x1+2x2]=[-4,5]
np.dot(b, a)
b @ a

d @ b

array([[  0,   1,   2],
       [ -6,  -1,   4],
       [-12,  -3,   6]])

### 判定論理値

In [70]:
# a = [0,1,2]
a >1
# b = [[-3,-2,-1],[0,1,2]]
b > 0
# 0ではない要素数を出力、Falseを0として扱う
np.count_nonzero(b >0)
# Trueを１として扱って足し算する
np.sum(b >0)
# Trueの要素があるかどうかを判定
np.any(b > 0)
# 要素が全てTrueだったらTrueを還す
np.all(b > 0)
# bから0以上要素を洗い出して新しい配列を作成
b[b > 0]
# 要素を比較
b == c
(b == c) | (a == b)
b[(b == c) | (a == b)]
# 誤差の範囲
np.allclose(b,c)
#誤差の範囲を引数で指定
np.allclose(b,c,atol=3)

False

### 関数とメソッド

In [73]:
#pythonのメソッド
a.sum()
#Numpyの関数
np.sum(a)
# 結果を同様、関数をメソッドの呼び出すをサポート
a.sum() == np.sum(a)

True