## 4.1.3 Numpyの各機能

In [2]:
import numpy as np
a = np.arange(3)
b = np.arange(-3, 3).reshape((2,3))
c = np.arange(1,7).reshape((2,3))
d = np.arange(6).reshape((3,2))
e = np.linspace(-1,1,10)
# 配列確認
print("a:",a)
print("b",b)
print("c:",c)
print("d:",d)
print("e:",e)

a: [0 1 2]
b [[-3 -2 -1]
 [ 0  1  2]]
c: [[1 2 3]
 [4 5 6]]
d: [[0 1]
 [2 3]
 [4 5]]
e: [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


In [2]:
# 要素確認
print("a:",a.shape)
print("b",b.shape)
print("c:",c.shape)
print("d:",d.shape)
print("e:",e.shape)

a: (3,)
b (2, 3)
c: (2, 3)
d: (3, 2)
e: (10,)


### ユニバーサルファンクション

In [3]:
# pythonで全ての要素の絶対値を得る例
li = [[-3,-2,-1],[0,1,2]]
new = []
for i, j in enumerate(li):
    new.append([])
    for k in j:
        new[i].append(abs(k))
new

[[3, 2, 1], [0, 1, 2]]

### `各種命令`

| No| 命令 | 説明 | 書き方 | 例 | 備考 |
|:---:|:---:|:---|:---|:---|:---|
| 01 | abs() | 配列の要素を一括変換(絶対値を取る) | np.abs(配列) | `x=np.abs([1, 2, 3,4]) | 配列の要素の絶対値を返す |
| 02 | sin() | sin関数を実行 | np.sin(配列) | `x=np.sin(e) | - |
| 03 | cos() | cos関数を実行 | np.cos(配列) | `x=np.cos(e) | - |
| 04 | log() | ネイピア数が底にする自然対数log計算 | np.log(配列) | `x=np.log(a) | - |
| 05 | log10() | 10が底にする自然対数log計算 | np.log10(配列) | `x=np.log10(a) | - |
| 06 | exp() | eのx乗を表示 | np.exp(配列) | `x=np.exp(a) | - |
| 07 | dot() | ドット積を計算 | np.dot(配列,配列) | `x=np.dot(a,b) | a@bと同様 |
| 08 | count_nonzero() | 0ではない要素数を出力 | np.count_nonzero(式) | `x=np.count_nonzero(a > 0) | - |
| 09 | sum() | 0ではない要素数を出力 | np.count_nonzero(式) | `x=np.count_nonzero(a > 0) | - |
| 010| count_nonzero() | 0ではない要素数を出力 | np.sum(式) | `x=np.sum(a > 0) | true:1 false:0で計算されるのでcount_nonzero()と同じ |
| 011| any() | trueが含まれているかを確認 | np.any(式) | `x=np.any(a > 0) | - |
| 012| all() | 全ての要素をtrueかを確認 | np.all(式) | `x=np.all(a > 0) | - |
| 013| allclose() | 全ての要素同じかどうか/誤差範囲 | np.allclose(配列,配列,atol=10) | `x=np.allcloe(a,b,alot=10) | - |

In [4]:
# numpyで全ての要素の絶対値を得る例
np.abs(li)

array([[3, 2, 1],
       [0, 1, 2]])

In [5]:
# sin関数
np.sin(e)

array([-0.84147098, -0.70169788, -0.52741539, -0.3271947 , -0.11088263,
        0.11088263,  0.3271947 ,  0.52741539,  0.70169788,  0.84147098])

In [6]:
# cos関数
np.cos(e)

array([0.54030231, 0.71247462, 0.84960756, 0.94495695, 0.99383351,
       0.99383351, 0.94495695, 0.84960756, 0.71247462, 0.54030231])

In [7]:
# log関数
np.log(a)

/Users/burgud/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718])

In [8]:
# log10関数(底が10)
np.log10(c)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125]])

In [9]:
# eのｘ
np.exp(a)

array([1.        , 2.71828183, 7.3890561 ])

### ブロードキャスト

In [14]:
a

array([0, 1, 2])

In [15]:
# 配列各要素に+10
a+10

array([10, 11, 12])

In [16]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [17]:
# aが2+3になり+b
a+b

array([[-3, -1,  1],
       [ 0,  2,  4]])

In [19]:
# aが3行まで拡張され、a1が3x3になれ足し算
a1 =a[:,np.newaxis]
a1

array([[0],
       [1],
       [2]])

In [20]:
a+a1

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [21]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
# 各要素から引き算
c - np.mean(c)

array([[-2.5, -1.5, -0.5],
       [ 0.5,  1.5,  2.5]])

In [24]:
# 各要素を2倍
b * 2 

array([[-6, -4, -2],
       [ 0,  2,  4]])

In [25]:
# 各要素を3乗
b ** 3

array([[-27,  -8,  -1],
       [  0,   1,   8]])

In [26]:
# aを２行にして引き算
b - a

array([[-3, -3, -3],
       [ 0,  0,  0]])

In [27]:
# aを２行にして掛け算
a * b

array([[ 0, -2, -2],
       [ 0,  1,  4]])

In [28]:
a /c

array([[0.        , 0.5       , 0.66666667],
       [0.        , 0.2       , 0.33333333]])

In [29]:
c / a

/Users/burgud/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, 2. , 1.5],
       [inf, 5. , 3. ]])

### ドット積

In [3]:
a

array([0, 1, 2])

In [4]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [5]:
# 2x3 行列 ＊ 1x3行列 = 1x2行列
# a =[0,1,2] x b=[[-3,-2,-1],[0,1,2]] = [(0x(-3)+1x(-2)+2x(-1)),0x0+1x1+2x2]=[-4,5]

np.dot(b, a)

array([-4,  5])

In [9]:
b @ a

array([-4,  5])

In [6]:
# 1x3 行列 ＊ 2x3行列 = ValueError
np.dot(a, b)

ValueError: shapes (3,) and (2,3) not aligned: 3 (dim 0) != 2 (dim 0)

AttributeError: 'list' object has no attribute 'type'

In [10]:
# 2x3 行列 ＊ 3x2行列 = 2x2行列
b @ d

array([[ -8, -14],
       [ 10,  13]])

In [8]:
# 3x2 行列 ＊ 2x3行列 = 3x3行列
d @ b

array([[  0,   1,   2],
       [ -6,  -1,   4],
       [-12,  -3,   6]])

### 判定論理値

In [33]:
# a = [0,1,2]
a >1

array([False, False,  True])

In [34]:
# b = [[-3,-2,-1],[0,1,2]]
b > 0

array([[False, False, False],
       [False,  True,  True]])

In [35]:
# 0ではない要素数を出力、Falseを0として扱う
np.count_nonzero(b >0)

2

In [36]:
# Trueを１として扱って足し算する
np.sum(b >0)

2

In [37]:
# Trueの要素があるかどうかを判定
np.any(b > 0)

True

In [38]:
# 要素が全てTrueだったらTrueを還す
np.all(b > 0)

False

In [39]:
# bから0以上要素を洗い出して新しい配列を作成
b[b > 0]

array([1, 2])

In [40]:
# 要素を比較
b == c

array([[False, False, False],
       [False, False, False]])

In [41]:
(b == c) | (a == b)

array([[False, False, False],
       [ True,  True,  True]])

In [42]:
b[(b == c) | (a == b)]

array([0, 1, 2])

In [43]:
# 誤差の範囲
np.allclose(b,c)

False

In [44]:
#誤差の範囲を引数で指定
np.allclose(b,c,atol=3)

False

### 関数とメソッド

In [45]:
#pythonのメソッド
a.sum()

3

In [46]:
#Numpyの関数
np.sum(a)

3

In [47]:
# 結果を同様、関数をメソッドの呼び出すをサポート
a.sum() == np.sum(a)

True