# 4.1 NumPy

### `各種命令`

| No| 命令 | 説明 | 書き方 | 例 | 備考 |
|:---:|:---:|:---|:---|:---|:---|
| 01 | array | 配列を生成 | array(リスト、タプルなど) | `x=np.array([1, 2, 3,4])`<br>`y = np.array([[1, 2, 3], [4, 5, 6]])` | np.array(range(1, 3))と同様 |
| 02 | shape | 配列の要素(構造)を調べる | 配列.shape | `x.shape` | 要素数をタブル型で返す |
| 03 | reshape | 配列の次元を変換する | reshape(1次元目の要素数, 2次元目の要素数) | `y1 = x.reshape(2, 2)` | 変換前後の要素数に注意 |
| 04 | ravel() | ２次元配列を１次元配列に変換 | 2次元配列.ravel() | `y2 =y.ravel() `  | 参照を返す |
| 05 | flatten() | ２次元配列を１次元配列に変換 | 2次元配列.flatten()  | `y3=y.flatten() ` | コピーを返す |
| 06 | dtype | 要素のデータ型を確認 |配列.dtype | `x.dtype` |dtype('int64')を返す、Numpyの由来のデータかた  |
| 07 | インデックス、スライス | 配列の要素にアクセス | 書き方：[開始:終了:間隔] | `x[2],y[:,2]` | - |
| 08 | arange |配列を返す | 書き方：np.arange(n,m,k)] | `np.arange(1,11,2)` | 引数1:開始位置、引数2:終了位置、引数3：スキップ |
| 09 | random.random | 乱数を生成する | random.rand(タプル) | `np.random.random((2,3))` | ある範囲の乱数 |
| 10 | random.rand | 乱数を生成する | random.rand(要素数, 次元数) | `np.random.rand(10, 1)` | rand：結果はrandomと同じ |
| 11 | random.randint | 乱数を生成する | random.randint(要素数, 次元数) | `np.random.randint(10, 1)` | ある範囲の任意の整数 |
| 12 | random.uniform | 乱数を生成する | random.uniform(開始, 終了,サイズ) | `np.random.uniform(0.0,0.5, size=(2,3))` | デフォルトは0〜1の小数点数を返す |
| 13 | random.randn | 乱数を生成する | random.randn要素数, 次元数) | `np.random.randn(2, 4)` | 標準正規分布乱数 |
| 14 | random.randnormal | 乱数を生成する | random.randnomal(要素数, 次元数,サイズ) | `np.random.rand(2, 4,3)` | 標準正規分布乱数、サイズを指定できる |
| 15 | zeros | 全てoのデータを生成 | np.zeros(要素数) | `np.zeros(2)` | - |
| 16 | ones | 全て1のデータを生成 | np.ones(要素数) | `np.ones(4)` | - |
| 17 | eys | 単位行列 | np.eys(サイズ) | `np.eys(3)` | - |
| 18 | full | 指定の値で配列を作成 | np.full(要素数,指定の値) | `np.full(3,3,14)` | [3.14,3.14,3.14] |
| 19 | nan | 数値ではない要素を作成 | np.nan | `a[1,2,np.nan]` | [1,2,nan] |
| 20 | linspace | ある範囲の等間隔数字を作成 | np.linspace(開始,終了,要素数) | `np.linspace(0,1,5)` |例： np.arange(0,1,0.25)と同様 |
| 21 | diff | 要素間の差分を返す | np.diff(配列) | `np.eys([1,3,5,9])` | - |
| 22 | concatenate | 配列を結合 | np.concatenate(配列) | `np.concatenate([a,a1],axis=1)` | axis=1は列方向結合 |
| 23 | hstack | 配列を結合（列方向） | np.hstack(配列) | `np.hstack([b,b1])` | - |
| 24 | vstack | 配列を結合（行方向） | np.vstack(配列) | `np.vstack([b,b2])` | - |
| 25 | hsplit | 配列を分割（列方向） | np.hsplit(分割する配列,１個の列数) | `np.hsplit(b3,[2])` | - |
| 26 | vsplit | 配列を分割（行方向） | np.vsplit(分割する配列,個目の行数) | `np.vsplit([b3,[2])` | - |
| 27 | T | 配列の行列の逆転する | np.T | `array([[1, 2, 8], [4, 5, 8]]).T` | [1,2,8]は1番目の列,[4,5,8]は2番目の列になる|
| 28 | newaxis | 次元追加（行と列） | np.newaxis | `a[np.newaxis, :]` | 例で行方向次元追加|
| 29 | meshgrid | グリットデータ作成 | np.meshgrid(配列,配列) | `np.meshgrid(m,n)` | - |

## 4.1.1 NumPyの概要
### NumPyとは
- NumPyは、Pythonで数値計算を効率的に行うためのライブラリです。NumPyはオープンソースで公開されており、個人／商用問わず、誰でも無料で利用することができます。

- NumPyを使うと、ベクトルや行列などの多次元配列の処理を容易に行うことができるようになります。またPythonだけで数値計算を行うのと比較して、非常に高速に処理を行うことができます（NumPyの内部はC、及びFortranというプログラム言語で実装されています）。

- 機械学習は、多次元配列に対して演算を行いながらモデルを学習していきます。NumPyを使うとそのような処理が効率的に行えるようになるため、Pythonで機械学習を行うには、NumPyは必須のライブラリとなっています。
 

### NumPyの使い方
- NumPyをインポート方法
`import numpy as np`


## 4.1.2 NumPyでデータを扱う

### １次元配列、2次元配列

In [4]:
pip install numpy

                                              0.0/15.0 MB ? eta -:--:--
                                              0.2/15.0 MB 4.6 MB/s eta 0:00:04
     -                                        0.6/15.0 MB 6.1 MB/s eta 0:00:03
     --                                       1.1/15.0 MB 7.9 MB/s eta 0:00:02
     ---                                      1.5/15.0 MB 7.8 MB/s eta 0:00:02
     ----                                     1.7/15.0 MB 7.5 MB/s eta 0:00:02
     -----                                    2.2/15.0 MB 7.8 MB/s eta 0:00:02
     -------                                  2.8/15.0 MB 8.4 MB/s eta 0:00:02
     --------                                 3.2/15.0 MB 8.5 MB/s eta 0:00:02
     ---------                                3.6/15.0 MB 8.6 MB/s eta 0:00:02
     ----------                               4.1/15.0 MB 8.8 MB/s eta 0:00:02
     -----------                              4.4/15.0 MB 9.0 MB/s eta 0:00:02
     -------------                            5.0/15.0 MB 9

In [5]:
import numpy as np

In [6]:
# １次元配列　ndarrayオブジェクト
a = np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
# 結果確認
print(a)

[1 2 3]


In [8]:
# type確認 
type(a)

numpy.ndarray

In [9]:
# 要素確認
a.shape

(3,)

In [10]:
b =np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
print(b)

[[1 2 3]
 [4 5 6]]


In [12]:
type(b)

numpy.ndarray

In [13]:
# 要素確認
b.shape


(2, 3)

### 変形(reshape,reval,flatten)、データ(dtype)

In [14]:
c1 = np.array([0,1,2,3,4,5])
c1

array([0, 1, 2, 3, 4, 5])

In [15]:
# c1 を2X3の２次元配列に変換
c2 = c1.reshape((2,3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
# c2 を１次元配列に変[参照]
c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [17]:
# c2 を１次元配列に変[コピー]
c4 = c2.flatten()
c4

array([0, 1, 2, 3, 4, 5])

In [18]:
# 配列要素のデータ型を確認
c4.dtype

dtype('int32')

In [19]:
# 型付け配列作成
d = np.array([1,2], dtype=np.int16)
d.dtype

dtype('int16')

In [20]:
# 型変換
d1=d.astype(np.float16)
d1.dtype

dtype('float16')

### インデックスとスライス

In [21]:
a

array([1, 2, 3])

In [22]:
# インデックス =0
a[0]

1

In [23]:
# スライス=1
a[1:]

array([2, 3])

In [24]:
# スライス=-1
a[-1]

3

In [25]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
# インデックス =0
b[0]

array([1, 2, 3])

In [27]:
# ２次元配列の１番目配列の２番目要素
b[0,1]

2

In [28]:
# スライス 全ての行、から２番目の列の要を取得
b[:,2]

array([3, 6])

In [29]:
# スライス 2番の行、全ての列の要を取得
b[1,:]

array([4, 5, 6])

In [30]:
# スライス 1番の行、２番目の要素からを取得
b[0,1:]

array([2, 3])

In [31]:
b[:,[0,2]]

array([[1, 3],
       [4, 6]])

### データ再代入、参照代入とコピー代入

In [32]:
a

array([1, 2, 3])

In [33]:
a[2]=4
a

array([1, 2, 4])

In [34]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
b[1,2]=7
b

array([[1, 2, 3],
       [4, 5, 7]])

In [36]:
# 全ての行の3番目要素に８を代入
b[:,2]=8
b

array([[1, 2, 8],
       [4, 5, 8]])

In [37]:
a1 = a
a1

array([1, 2, 4])

In [38]:
a1[1] =5
a1

array([1, 5, 4])

In [39]:
# aとa1は同じ結果、原因aとa1は参照関係
a

array([1, 5, 4])

In [58]:
a2 =a.copy()
a2

array([1, 5, 4])

In [128]:
a2[0] = 6
a2

array([6, 5, 4])

In [145]:
# aとa2は異なる結果、原因はaとa2はコピー関係
a

array([1, 5, 4])

In [61]:
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [62]:
c3 = c2.ravel()
c4 = c2.flatten()
c3[0] =6
c4[1] = 7

In [63]:
c3

array([6, 1, 2, 3, 4, 5])

In [173]:
c4

array([0, 7, 2, 3, 4, 5])

In [65]:
# c2の結果はc3と同じく、c4と異なる、原因はravel()は参照メソッド、flatten()はコピーメソッド
c2

array([[6, 1, 2],
       [3, 4, 5]])

In [68]:
# pythoｎのスライスの結果はコピー
py_list1 = [0,1]
py_list2 = py_list1[:]
py_list2[0] = 2
print(py_list1)
print(py_list2)

[0, 1]
[2, 1]


In [69]:
# Numpyのスライスの結果は参照
np_array1 = np.array([0,1])
np_array2 = np_array1[:]
np_array2[0] = 2
print(np_array1)
print(np_array2)

[2 1]
[2 1]


### 数列を返す

In [70]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
# 1-11間の連続数字を返す
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
# 引数1:開始位置、引数2:終了位置、引数3：スキップ
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

### 乱数

In [78]:
# タプルは引数
f = np.random.random((3,2))
f

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [80]:
# 固定乱数を作るため
np.random.seed(123)
# 複数の引数
g = np.random.rand(3,2)
g

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [81]:
np.random.seed(123)
h = np.random.randint(1,10)
h

3

In [83]:
# ある範囲内の任意の小数値を生成
np.random.seed(123)
j= np.random.uniform(0.0,5.0,size=(2,3))
j

array([[3.48234593, 1.43069667, 1.13425727],
       [2.75657385, 3.59734485, 2.1155323 ]])

In [84]:

# 標準正規分布
np.random.seed(123)
i = np.random.randn(4,2)
i

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654],
       [-2.42667924, -0.42891263]])

In [87]:

#平均、標準偏差、size(形状)を引数として正規分布乱数を取得
np.random.seed(123)
k = np.random.normal(4,2,6)
k

array([1.82873879, 5.99469089, 4.565957  , 0.98741057, 2.8427995 ,
       7.30287307])

### 同じ要素の数列を作る

In [88]:
# 要素が全て0.
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [89]:
# 要素が全1.
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [93]:
# 要素が対角が1.その他が0.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 指定値で埋める

In [95]:
# 3.14を３つ埋める
np.full(3,3.14)

array([3.14, 3.14, 3.14])

In [96]:
# 2x4の行列にpiを埋める
np.full((2,4),np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [97]:
# Not a Numberの宣言
np.array([1,2,np.nan])

array([ 1.,  2., nan])

In [98]:
# 均等割りデータを作る(0~1の間5個のよそを作る)
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [100]:
# 均等割りデータを作る(0~1の間5個のよそを作る)
np.arange(0.0,1.1,0.25)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [101]:
0〜pi間のデータを20作成
np.linspace(0,np.pi,21)

array([0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853,
       0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669,
       1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486,
       2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302,
       3.14159265])

### 差分を返す

In [102]:
m = np.array([2,2,6,1,3])
# 要素間の差分を返す
np.diff(m)

array([ 0,  4, -5,  2])

### 連携

In [130]:
l = [1,5,4]
l1 = [1,5,4]
print(l)
print(l1)

[1, 5, 4]
[1, 5, 4]


In [131]:
# l+l1
np.concatenate([l,l1])

array([1, 5, 4, 1, 5, 4])

In [105]:
# ２次元配列の連携、axis=1:列方向増やす
b = np.array([[1,2,8],[4,5,8]])
b1 = np.array([[10],[20]])
print(b)
print(b1)

[[1 2 8]
 [4 5 8]]
[[10]
 [20]]


In [106]:
# b+b1
np.concatenate([b,b1],axis=1)

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [108]:
# b+b1 上記と同様
np.hstack([b,b1])

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [109]:
b2 = np.array([30,60,45])
b2

array([30, 60, 45])

In [110]:
# 行方向増やす
b3 = np.vstack([b,b2])
b3

array([[ 1,  2,  8],
       [ 4,  5,  8],
       [30, 60, 45]])

### 分割

In [111]:
# 列毎に分割
first,second = np.hsplit(b3,[2])

In [112]:
first

array([[ 1,  2],
       [ 4,  5],
       [30, 60]])

In [113]:
second

array([[ 8],
       [ 8],
       [45]])

In [114]:
# 行毎に分割
first1,second2 = np.vsplit(b3,[2])

In [115]:
first1

array([[1, 2, 8],
       [4, 5, 8]])

In [116]:
second2

array([[30, 60, 45]])

### 転置、次元追加

In [117]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [118]:
# 行列を転置
b.T

array([[1, 4],
       [2, 5],
       [8, 8]])

In [146]:
a

array([1, 5, 4])

In [147]:
# 行方向に次元追加
a[np.newaxis, :]

array([[1, 5, 4]])

In [148]:
# 列方向に次元追加
a[:,np.newaxis]

array([[1],
       [5],
       [4]])

### グリッドデータの作成

In [114]:
m = np.arange(0,4)
n = np.arange(4,7)
# xxにmを行方向に3回(nの長さ)コピーして入れる 
# yy にnを列方向に4回(ｍの長さ)コピーして入れる
xx,yy = np.meshgrid(m,n)
print(xx)
print(yy)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]]
